export const LOCATION_TAB_COMPLETED = 'ORDER_STEP/LOCATION_TAB_COMPLETED';
export const MODEL_TAB_COMPLETED = 'ORDER_STEP/MODEL_TAB_COMPLETED';
export const ADVANCED_TAB_COMPLETED = 'ORDER_STEP/ADVANCED_TAB_COMPLETED';
