export const UPLOADING_ORDER_START = 'ORDER_STATUS/UPLOADING_ORDER_START';
export const UPLOADING_ORDER_END = 'ORDER_STATUS/UPLOADING_ORDER_END';
export const GET_ORDER_STATUS_DATA = 'ORDER_STATUS/GET_ORDER_STATUS_DATA';
export const DELETE_ORDER_STATUS_DATA = 'ORDER_STATUS/DELETE_ORDER_STATUS_DATA';
