export const LOAD_POINTS_SUCCESS = 'POINTS_DATA/LOAD_SUCCESS';
export const SHOW_POINTS_LOADER = 'POINTS_DATA/SHOW_LOADER';
export const HIDE_POINTS_LOADER = 'POINTS_DATA/HIDE_LOADER';
export const CHANGE_CITY_COORDS = 'POINTS_DATA/CHANGE_CITY_COORDINATES';
export const CHANGE_MARKER_COORDS = 'POINTS_DATA/CHANGE_MARKER_COORDINATES';
