export const SELECT_ITEM = 'RADIO_BUTTON/SELECT_ITEM';
export const RADIO_BTN_CAR_ID = 'RADIO_BUTTON/RADIO_BTN_CAR_ID';
export const RADIO_BTN_COLOR_ID = 'RADIO_BUTTON/RADIO_BTN_COLOR_ID';
export const RADIO_BTN_TARIFF_ID = 'RADIO_BUTTON/RADIO_BTN_TARIFF_ID';
export const RADIO_BTN_ADVANCED_ID = 'RADIO_BUTTON/RADIO_BTN_ADVANCED_ID';
